// Code generated by protoc-gen-go.
// source: Product.proto
// DO NOT EDIT!

package protos

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type Product struct {
	Name   string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Id     int32  `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Vendor string `protobuf:"bytes,3,opt,name=vendor" json:"vendor,omitempty"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}

func init() {
}
